---
title: "Predicting CAD ROC curve"
author: "Daniel Lans"
date: "6/29/2019"
output: html_document
---

### Importing Data and Summary
```{r importing data, warning=FALSE}
cad <- read.csv("~/Documents/Analytics/Public Data/mendeley/mendeleydata.csv", header=T)

# Rows and Columns
cat("----- Rows and Columns of Raw Data -----")
cat(paste("\nRows: ", nrow(cad), "\nColumns: ", ncol(cad)))

# Missing Data
cat("\n\n----- Missing Data -----\n")
missing_counts <- data.frame(sapply(cad, function(x) sum(is.na(x))))
names(missing_counts) <- "missCount"
subset(missing_counts, missing_counts[,1] > 0)

# Blank columns (variable X) split up types of variables
splitX1 <- grep('^X$', colnames(cad))
splitX2 <- grep('^X.1$', colnames(cad))
splitX3 <- grep('^X.2$', colnames(cad))

## Demographics:
demo_vars <- names(cad[1:splitX1-1])
med_vars <- names(cad[(splitX1+1):(splitX2-1)])
lab_vars <- names(cad[(splitX2+1):(splitX3-1)])
protein_vars <- names(cad[(splitX3+1):(ncol(cad))])

cat("\n----- Demographics -----\n", demo_vars)
cat("\n\n----- Medication Use -----\n", med_vars)
cat("\n\n----- Lab Tests -----\n", lab_vars)
cat("\n\n----- Proteins -----\n", length(protein_vars), "proteins")

```

### Outcome: Absence of Coronary Artery Disease
```{r Coronary Artery Disease, warning=FALSE}
cat("\n----- Outcome: CAD = 0, No CAD = 1 -----\n")
table(cad$CCTA.NoCAD)
apply(prop.table(table(cad$CCTA.NoCAD))*100, 1, function(x) sprintf( "%.2f%%", x))

cat("\n----- Outcome: HRP = 0, No HRP = 1 -----\n")
table(cad$CCTA.HRP)
apply(prop.table(table(cad$CCTA.HRP))*100, 1, function(x) sprintf( "%.2f%%", x))
```


### Splitting the data
```{r, warning=FALSE}
library(caret)
# folds <- createFolds(factor(cad$CCTA.HRP), k = 5, list = T)
# 
# head(folds)
# cad[folds[[1]],]

# Assign blocks to data set
kfolder <- function(data, n_folds){
  set.seed(500)
  
  # set data frame
  d <- data
  
  # store data frame folds in a list
  foldList <- list()
  
  # create k-1 folds
  for(i in seq(n_folds - 1)){
    foldi <- d[sample(nrow(d), nrow(data) / n_folds),]
    foldList[[i]] <- foldi
    d <- d[!(rownames(d) %in% rownames(foldi)),]
  }
  
  # place remaining data in final fold
  foldList[[n_folds]] <- d
  
  # Return the list object
  return(foldList)
}

# k-fold Cross-validation
nfoldselect <- nrow(cad)
fold_list <- kfolder(cad, nfoldselect)

```

```{r, warning=FALSE}
library(xgboost)
cvModeler <- function(df, n_folds){
  set.seed(100)
  predprobs <- list()
  for(i in seq(n_folds)){
    
    # Train and Test Data
    train <- df[!(rownames(df) %in% rownames(fold_list[[i]])),]
    test <- df[(rownames(df) %in% rownames(fold_list[[i]])),]
    
    X <- as.matrix(train[, names(train) %in% protein_vars])
    y <- as.matrix(train$CCTA.NoCAD)
    Xtest <- as.matrix(test[, names(test) %in% protein_vars])
    ytest <- as.matrix(test$CCTA.NoCAD)

    dtrain <- xgb.DMatrix(data = X, label = y)
    xgb <- xgboost(data = dtrain, 
                   max.depth = 6, 
                   eta = .7, 
                   nthread = 2, 
                   nrounds = 20, 
                   objective = "binary:logistic",
                   verbose = 0)
    
    predprobs[[i]] <- predict(xgb, as.matrix(Xtest))
  }
  return(predprobs)
}
modelpreds <- cvModeler(cad, nfoldselect)

# assign indexes to predictions
foldrows <- list()
for(i in 1:nfoldselect){
  foldrows[[i]] <- rownames(fold_list[[i]])
}
fold_rowindex <- unlist(foldrows)
predictions <- data.frame(phat = unlist(modelpreds))
rownames(predictions) <- fold_rowindex
predictions <- predictions[order(as.numeric(rownames(predictions))),,drop=FALSE]


library(ROCR)
pred <- prediction(predictions$phat,as.factor(cad$CCTA.NoCAD))
perf <- performance(pred, "tpr", "fpr")
auc <- performance(pred,"auc")
auc <- unlist(slot(auc, "y.values"))
plot(perf)
abline(a=0,b=1)
text(0.8,0.2,labels=paste("AUC = ",round(auc,3)))
title("ROC Curve")

```



### Accuracy 
```{r, warning=FALSE}
# sensitivity
sn_index <- min(which(perf@y.values[[1]] >= 0.95))+1
pr_cutoff <- perf@alpha.values[[1]][sn_index]

# Confusion Matrix
preds_class <- ifelse(predictions$phat > pr_cutoff, 1, 0)
confusionMatrix(as.factor(preds_class),as.factor(cad$CCTA.NoCAD), positive="1")
```

